const { Op } = require('sequelize');

module.exports = {
  'Op.and': Op.and,
  'Op.or': Op.or,
  'Op.eq': Op.eq,
  'Op.ne': Op.ne,
  'Op.is': Op.is,
  'Op.not': Op.not,
  'Op.col': Op.col,
  'Op.gt': Op.gt,
  'Op.gte': Op.gte,
  'Op.lt': Op.lt,
  'Op.lte': Op.lte,
  'Op.between': Op.between,
  'Op.notBetween': Op.notBetween,
  'Op.all': Op.all,
  'Op.in': Op.in,
  'Op.notIn': Op.notIn,
  'Op.like': Op.like,
  'Op.notLike': Op.notLike,
  'Op.startsWith': Op.startsWith,
  'Op.endsWith': Op.endsWith,
  'Op.substring': Op.substring,
  'Op.iLike': Op.iLike,
  'Op.notILike': Op.notILike,
  'Op.regexp': Op.regexp,
  'Op.notRegexp': Op.notRegexp,
  'Op.iRegexp': Op.iRegexp,
  'Op.notIRegexp': Op.notIRegexp,
  'Op.any': Op.any,
};
